package crud

import (
	"sync"
	"time"
)

// LookupCache stores sanitized lookup pages. The key is generated by Service
// from server-owned resource metadata, trusted scope, and normalized query
// values; clients never provide a cache key.
type LookupCache interface {
	Get(string) (LookupPage, bool)
	Set(string, LookupPage)
}

// MemoryLookupCacheOptions bounds the process-local read-through cache.
type MemoryLookupCacheOptions struct {
	MaxEntries int
	TTL        time.Duration
}

type lookupCacheEntry struct {
	page      LookupPage
	expiresAt time.Time
	usedAt    uint64
}

// MemoryLookupCache is a bounded, concurrent cache suitable for immutable
// reference catalogs and short-lived tenant lookup pages. A host running
// multiple instances may provide a distributed LookupCache instead.
type MemoryLookupCache struct {
	mu         sync.Mutex
	entries    map[string]lookupCacheEntry
	maxEntries int
	ttl        time.Duration
	sequence   uint64
}

// NewMemoryLookupCache constructs a bounded cache. Zero options use safe
// defaults rather than disabling caching.
func NewMemoryLookupCache(options MemoryLookupCacheOptions) *MemoryLookupCache {
	if options.MaxEntries <= 0 {
		options.MaxEntries = 512
	}
	if options.TTL <= 0 {
		options.TTL = 5 * time.Minute
	}
	return &MemoryLookupCache{entries: make(map[string]lookupCacheEntry), maxEntries: options.MaxEntries, ttl: options.TTL}
}

func (cache *MemoryLookupCache) Get(key string) (LookupPage, bool) {
	if cache == nil || key == "" {
		return LookupPage{}, false
	}
	now := time.Now()
	cache.mu.Lock()
	entry, ok := cache.entries[key]
	if !ok || !now.Before(entry.expiresAt) {
		if ok {
			delete(cache.entries, key)
		}
		cache.mu.Unlock()
		return LookupPage{}, false
	}
	cache.sequence++
	entry.usedAt = cache.sequence
	cache.entries[key] = entry
	cache.mu.Unlock()
	return cloneLookupPage(entry.page), true
}

func (cache *MemoryLookupCache) Set(key string, page LookupPage) {
	if cache == nil || key == "" {
		return
	}
	cache.mu.Lock()
	defer cache.mu.Unlock()
	cache.sequence++
	cache.entries[key] = lookupCacheEntry{page: cloneLookupPage(page), expiresAt: time.Now().Add(cache.ttl), usedAt: cache.sequence}
	for len(cache.entries) > cache.maxEntries {
		var oldestKey string
		var oldest uint64
		for candidate, entry := range cache.entries {
			if oldestKey == "" || entry.usedAt < oldest {
				oldestKey, oldest = candidate, entry.usedAt
			}
		}
		delete(cache.entries, oldestKey)
	}
}

// Clear removes all process-local entries. Hosts can call it after an
// explicit catalog refresh or tenant policy change.
func (cache *MemoryLookupCache) Clear() {
	if cache == nil {
		return
	}
	cache.mu.Lock()
	cache.entries = make(map[string]lookupCacheEntry)
	cache.mu.Unlock()
}

func cloneLookupPage(page LookupPage) LookupPage {
	clone := page
	clone.Options = append([]LookupOption(nil), page.Options...)
	if page.Total != nil {
		total := *page.Total
		clone.Total = &total
	}
	return clone
}
