// Package sqladapter provides SQL persistence adapters for clear.crud.
// It imports database/sql but never imports or selects a database driver.
package sqladapter

import (
	"context"
	"database/sql"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	crud "github.com/clear-platform-br/clear-crud"
)

var identifierPattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// Identifier is a server-validated SQL identifier. It is never built from an
// HTTP value, field value, or tenant value.
type Identifier string

// NewIdentifier validates an SQL table or column identifier for simple_table.
func NewIdentifier(value string) (Identifier, error) {
	if !identifierPattern.MatchString(value) {
		return "", fmt.Errorf("sqladapter: invalid identifier %q", value)
	}
	return Identifier(value), nil
}

// TableDefinition maps one conventional table to a clear.crud DataSource.
type TableDefinition struct {
	Table    Identifier
	IDColumn Identifier
	// Global marks an explicitly read-only reference table with no tenant
	// columns. It is never inferred from a table name.
	Global bool
	// IDField optionally maps a create-only public field to IDColumn. Without
	// it, SQLite generates the opaque record ID.
	IDField       crud.FieldKey
	VersionColumn Identifier
	ScopeColumns  map[string]Identifier
	// ArchiveColumn preserves the conventional false/true archive mapping.
	ArchiveColumn *Identifier
	// ArchiveState maps an explicit active/archived state column.
	ArchiveState *ArchiveState
	// Managed values are server-provided technical columns, never form fields.
	Managed []ManagedColumn
	Fields  map[crud.FieldKey]Identifier
}

// ArchiveState maps application state values for the archive policy.
type ArchiveState struct {
	Column        Identifier
	ActiveValue   crud.Value
	ArchivedValue crud.Value
}

// ManagedValueSource identifies a server-side source for a technical column.
type ManagedValueSource string

const (
	ManagedValueNone   ManagedValueSource = ""
	ManagedValueScope  ManagedValueSource = "scope"
	ManagedValueUTCNow ManagedValueSource = "utc_now"
)

// ManagedValue resolves only from trusted server scope or the server clock.
type ManagedValue struct {
	Source   ManagedValueSource
	ScopeKey string
}

// ManagedColumn is written on create and/or update. A zero phase value leaves
// that phase untouched.
type ManagedColumn struct {
	Column   Identifier
	OnCreate ManagedValue
	OnUpdate ManagedValue
}

// ManagedFromScope returns a trusted-scope managed value.
func ManagedFromScope(key string) ManagedValue {
	return ManagedValue{Source: ManagedValueScope, ScopeKey: key}
}

// ManagedUTCNow returns an RFC3339Nano UTC timestamp generated by the server.
func ManagedUTCNow() ManagedValue { return ManagedValue{Source: ManagedValueUTCNow} }

// SimpleTable implements a SQLite simple_table resource and its UnitOfWork.
// Its config is server-owned and validated before it can serve a request.
type SimpleTable struct {
	db    *sql.DB
	table TableDefinition
}

// NewSimpleTable constructs a SQLite adapter without importing a SQLite driver.
func NewSimpleTable(db *sql.DB, table TableDefinition) (*SimpleTable, error) {
	if db == nil {
		return nil, fmt.Errorf("sqladapter: nil database")
	}
	if err := validateTable(table); err != nil {
		return nil, err
	}
	return &SimpleTable{db: db, table: cloneTable(table)}, nil
}

// Capabilities reports guarantees supplied by SQLite simple_table.
func (source *SimpleTable) Capabilities(context.Context) crud.Capabilities {
	return crud.Capabilities{
		crud.CapabilityTotalCount:     {},
		crud.CapabilityOffsetPage:     {},
		crud.CapabilityAtomicVersion:  {},
		crud.CapabilityUnitOfWork:     {},
		crud.CapabilityContainsSearch: {},
		crud.CapabilityArchive:        {},
		crud.CapabilityHardDelete:     {},
		crud.CapabilityLookup:         {},
	}
}

// Within starts a transaction and makes it available to source operations
// through their context. A returned error rolls all mutations back.
func (source *SimpleTable) Within(ctx context.Context, operation func(context.Context) error) error {
	transaction, err := source.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	transactionContext := context.WithValue(ctx, transactionKey{}, transaction)
	if err := operation(transactionContext); err != nil {
		_ = transaction.Rollback()
		return err
	}
	return transaction.Commit()
}

// List returns records from exactly one trusted scope.
func (source *SimpleTable) List(ctx context.Context, scope crud.Scope, query crud.Query) (crud.Page, error) {
	where, args, err := source.where(scope, query)
	if err != nil {
		return crud.Page{}, err
	}
	columns := source.selectColumns()
	statement := "SELECT " + columns + " FROM " + quote(source.table.Table) + " WHERE " + where + source.order(query.Sort)
	args = append(args, int64(query.Page.Size), int64((query.Page.Number-1)*uint64(query.Page.Size)))
	statement += " LIMIT ? OFFSET ?"
	rows, err := source.executor(ctx).QueryContext(ctx, statement, args...)
	if err != nil {
		return crud.Page{}, err
	}
	defer rows.Close()
	records, err := source.records(rows)
	if err != nil {
		return crud.Page{}, err
	}
	if err := rows.Err(); err != nil {
		return crud.Page{}, err
	}
	countStatement := "SELECT COUNT(*) FROM " + quote(source.table.Table) + " WHERE " + where
	var count uint64
	if err := source.executor(ctx).QueryRowContext(ctx, countStatement, args[:len(args)-2]...).Scan(&count); err != nil {
		return crud.Page{}, err
	}
	return crud.Page{Records: records, Page: query.Page.Number, Size: query.Page.Size, Total: &count}, nil
}

// Get loads one record in the supplied trusted scope.
func (source *SimpleTable) Get(ctx context.Context, scope crud.Scope, id crud.RecordID) (crud.Record, error) {
	where, args, err := source.scopeWhere(scope)
	if err != nil {
		return crud.Record{}, err
	}
	activeWhere, activeArgs := source.activeWhere()
	args = append([]any{id}, args...)
	args = append(args, activeArgs...)
	statement := "SELECT " + source.selectColumns() + " FROM " + quote(source.table.Table) + " WHERE " + quote(source.table.IDColumn) + " = ? AND " + where + activeWhere
	row := source.executor(ctx).QueryRowContext(ctx, statement, args...)
	record, err := source.scanRecord(row)
	if err == sql.ErrNoRows {
		return crud.Record{}, public(crud.ErrorNotFound)
	}
	return record, err
}

// Create inserts a full mutation and reads the generated opaque record ID.
func (source *SimpleTable) Create(ctx context.Context, scope crud.Scope, mutation crud.Mutation) (crud.Record, error) {
	if source.table.Global {
		return crud.Record{}, public(crud.ErrorInvalidRequest)
	}
	columns, values, args, err := source.mutationValues(scope, mutation, crud.ActionCreate)
	if err != nil {
		return crud.Record{}, err
	}
	columns = append(columns, quote(source.table.VersionColumn))
	values = append(values, "?")
	args = append(args, int64(1))
	statement := "INSERT INTO " + quote(source.table.Table) + " (" + strings.Join(columns, ", ") + ") VALUES (" + strings.Join(values, ", ") + ")"
	result, err := source.executor(ctx).ExecContext(ctx, statement, args...)
	if err != nil {
		return crud.Record{}, err
	}
	if source.table.IDField != "" {
		id, ok := mutation.Fields[source.table.IDField]
		if !ok || stringValue(id) == "" {
			return crud.Record{}, public(crud.ErrorInvalidRequest)
		}
		return source.Get(ctx, scope, crud.RecordID(stringValue(id)))
	}
	id, err := result.LastInsertId()
	if err != nil {
		return crud.Record{}, err
	}
	return source.Get(ctx, scope, crud.RecordID(strconv.FormatInt(id, 10)))
}

// Update replaces a full mutation only while its version matches.
func (source *SimpleTable) Update(ctx context.Context, scope crud.Scope, id crud.RecordID, version crud.Version, mutation crud.Mutation) (crud.Record, error) {
	if source.table.Global {
		return crud.Record{}, public(crud.ErrorInvalidRequest)
	}
	// Updates from the generic contract may omit server-owned or hidden
	// columns. Preserve their persisted values before building the adapter's
	// full-column SQL statement; nil must remain an intentional value for a
	// field that the mutation explicitly supplied.
	current, err := source.Get(ctx, scope, id)
	if err != nil {
		return crud.Record{}, err
	}
	fields := make(crud.Fields, len(current.Fields)+len(mutation.Fields))
	for key, value := range current.Fields {
		fields[key] = value
	}
	for key, value := range mutation.Fields {
		fields[key] = value
	}
	mutation.Fields = fields
	_, _, allArgs, err := source.mutationValues(scope, mutation, crud.ActionUpdate)
	if err != nil {
		return crud.Record{}, err
	}
	args := append([]any(nil), allArgs[len(source.table.ScopeColumns):]...)
	assignments := source.assignments(crud.ActionUpdate)
	where, scopeArgs, err := source.scopeWhere(scope)
	if err != nil {
		return crud.Record{}, err
	}
	args = append(args, id)
	args = append(args, scopeArgs...)
	activeWhere, activeArgs := source.activeWhere()
	args = append(args, activeArgs...)
	args = append(args, version)
	statement := "UPDATE " + quote(source.table.Table) + " SET " + assignments + " WHERE " + quote(source.table.IDColumn) + " = ? AND " + where + activeWhere + " AND " + quote(source.table.VersionColumn) + " = ?"
	result, err := source.executor(ctx).ExecContext(ctx, statement, args...)
	if err != nil {
		return crud.Record{}, err
	}
	changed, err := result.RowsAffected()
	if err != nil {
		return crud.Record{}, err
	}
	if changed != 1 {
		return crud.Record{}, public(crud.ErrorConflict)
	}
	return source.Get(ctx, scope, id)
}

// Delete archives or physically deletes one versioned record.
func (source *SimpleTable) Delete(ctx context.Context, scope crud.Scope, id crud.RecordID, version crud.Version, mode crud.DeleteMode) error {
	if source.table.Global {
		return public(crud.ErrorDeleteRestricted)
	}
	if mode == crud.DeleteModeNone {
		return public(crud.ErrorDeleteRestricted)
	}
	where, args, err := source.scopeWhere(scope)
	if err != nil {
		return err
	}
	args = append([]any{id}, args...)
	activeWhere, activeArgs := source.activeWhere()
	args = append(args, activeArgs...)
	var statement string
	switch mode {
	case crud.DeleteModeArchive:
		archiveColumn, _, archived, ok := source.archiveState()
		if !ok {
			return public(crud.ErrorDeleteRestricted)
		}
		assignments, managedArgs, err := source.archiveAssignments(scope, archiveColumn, archived)
		if err != nil {
			return err
		}
		args = append(managedArgs, args...)
		args = append(args, version)
		statement = "UPDATE " + quote(source.table.Table) + " SET " + assignments + " WHERE " + quote(source.table.IDColumn) + " = ? AND " + where + activeWhere + " AND " + quote(source.table.VersionColumn) + " = ?"
	case crud.DeleteModeHardDelete:
		args = append(args, version)
		statement = "DELETE FROM " + quote(source.table.Table) + " WHERE " + quote(source.table.IDColumn) + " = ? AND " + where + activeWhere + " AND " + quote(source.table.VersionColumn) + " = ?"
	default:
		return public(crud.ErrorDeleteRestricted)
	}
	result, err := source.executor(ctx).ExecContext(ctx, statement, args...)
	if err != nil {
		if mode == crud.DeleteModeHardDelete && isForeignKeyViolation(err) {
			// Referential integrity belongs to the database. Do not issue a
			// preflight SELECT: it would add latency and still race the DELETE.
			return public(crud.ErrorDeleteRestricted)
		}
		return err
	}
	changed, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if changed != 1 {
		return public(crud.ErrorConflict)
	}
	return nil
}

// Lookup returns bounded value/label pairs from this server-registered table.
// The target columns and dependency fields arrive only from Service, never
// from the HTTP request.
func (source *SimpleTable) Lookup(ctx context.Context, scope crud.Scope, query crud.LookupQuery) (crud.LookupPage, error) {
	if query.ValueField == "" || query.LabelField == "" || query.Size == 0 || query.Size > 100 {
		return crud.LookupPage{}, public(crud.ErrorInvalidRequest)
	}
	valueColumn, ok := source.lookupColumn(query.ValueField, true)
	if !ok {
		return crud.LookupPage{}, public(crud.ErrorInvalidRequest)
	}
	labelColumn, ok := source.lookupColumn(query.LabelField, false)
	if !ok {
		return crud.LookupPage{}, public(crud.ErrorInvalidRequest)
	}
	where, args, err := source.scopeWhere(scope)
	if err != nil {
		return crud.LookupPage{}, err
	}
	activeWhere, activeArgs := source.activeWhere()
	where += activeWhere
	args = append(args, activeArgs...)
	keys := make([]string, 0, len(query.Dependencies))
	for key := range query.Dependencies {
		keys = append(keys, string(key))
	}
	sort.Strings(keys)
	for _, key := range keys {
		column, ok := source.table.Fields[crud.FieldKey(key)]
		if !ok {
			return crud.LookupPage{}, public(crud.ErrorInvalidRequest)
		}
		where += " AND " + quote(column) + " = ?"
		args = append(args, query.Dependencies[crud.FieldKey(key)])
	}
	for _, filter := range query.FixedFilters {
		column, ok := source.table.Fields[filter.Field]
		if !ok || len(filter.Values) == 0 || len(filter.Values) > 100 {
			return crud.LookupPage{}, public(crud.ErrorInvalidRequest)
		}
		for _, value := range filter.Values {
			if !lookupFilterValue(value) {
				return crud.LookupPage{}, public(crud.ErrorInvalidRequest)
			}
		}
		if len(filter.Values) == 1 {
			where += " AND " + quote(column) + " = ?"
			args = append(args, filter.Values[0])
			continue
		}
		where += " AND " + quote(column) + " IN (" + lookupPlaceholders(len(filter.Values)) + ")"
		args = append(args, filter.Values...)
	}
	if query.Search != "" {
		where += " AND (LOWER(CAST(" + quote(labelColumn) + " AS TEXT)) LIKE LOWER(?) OR CAST(" + quote(valueColumn) + " AS TEXT) = ?)"
		args = append(args, "%"+query.Search+"%", query.Search)
	}
	offset := uint64(0)
	if query.Cursor != "" {
		parsed, parseErr := strconv.ParseUint(query.Cursor, 10, 63)
		if parseErr != nil {
			return crud.LookupPage{}, public(crud.ErrorInvalidRequest)
		}
		offset = parsed
	}
	if offset > uint64(1<<63-1)-uint64(query.Size) {
		return crud.LookupPage{}, public(crud.ErrorInvalidRequest)
	}
	statement := "SELECT " + quote(valueColumn) + ", " + quote(labelColumn) + " FROM " + quote(source.table.Table) + " WHERE " + where + " ORDER BY " + quote(labelColumn) + " ASC, " + quote(valueColumn) + " ASC LIMIT ? OFFSET ?"
	args = append(args, int64(query.Size), int64(offset))
	rows, err := source.executor(ctx).QueryContext(ctx, statement, args...)
	if err != nil {
		return crud.LookupPage{}, err
	}
	defer rows.Close()
	options := make([]crud.LookupOption, 0, query.Size)
	for rows.Next() {
		var value, label any
		if err := rows.Scan(&value, &label); err != nil {
			return crud.LookupPage{}, err
		}
		options = append(options, crud.LookupOption{Value: sqlValue(value), Label: stringValue(label)})
	}
	if err := rows.Err(); err != nil {
		return crud.LookupPage{}, err
	}
	page := crud.LookupPage{Options: options}
	if len(options) == int(query.Size) {
		page.NextCursor = strconv.FormatUint(offset+uint64(query.Size), 10)
	}
	return page, nil
}

func lookupFilterValue(value crud.Value) bool {
	switch value.(type) {
	case string, bool, int64:
		return true
	default:
		return false
	}
}

func lookupPlaceholders(count int) string {
	return strings.TrimSuffix(strings.Repeat("?,", count), ",")
}

func (source *SimpleTable) lookupColumn(field crud.FieldKey, allowID bool) (Identifier, bool) {
	if allowID && field == "id" {
		return source.table.IDColumn, true
	}
	column, ok := source.table.Fields[field]
	return column, ok
}

type executor interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

type transactionKey struct{}

func (source *SimpleTable) executor(ctx context.Context) executor {
	if transaction, ok := ctx.Value(transactionKey{}).(*sql.Tx); ok {
		return transaction
	}
	return source.db
}

func validateTable(table TableDefinition) error {
	if table.Table == "" || table.IDColumn == "" || table.VersionColumn == "" || len(table.Fields) == 0 || !table.Global && len(table.ScopeColumns) == 0 {
		return fmt.Errorf("sqladapter: table, id, version, scope and fields are required")
	}
	if table.Global && len(table.ScopeColumns) != 0 {
		return fmt.Errorf("sqladapter: global table cannot declare scope columns")
	}
	if table.IDField != "" && table.Fields[table.IDField] != table.IDColumn {
		return fmt.Errorf("sqladapter: id field must map to id column")
	}
	if table.ArchiveColumn != nil && table.ArchiveState != nil {
		return fmt.Errorf("sqladapter: archive column and archive state are exclusive")
	}
	if table.ArchiveState != nil && !validIdentifier(table.ArchiveState.Column) {
		return fmt.Errorf("sqladapter: invalid archive state")
	}
	for key, column := range table.ScopeColumns {
		if key == "" || !validIdentifier(column) {
			return fmt.Errorf("sqladapter: invalid scope column")
		}
	}
	for key, column := range table.Fields {
		if key == "" || !validIdentifier(column) {
			return fmt.Errorf("sqladapter: invalid field column")
		}
	}
	if !validIdentifier(table.Table) || !validIdentifier(table.IDColumn) || !validIdentifier(table.VersionColumn) || table.ArchiveColumn != nil && !validIdentifier(*table.ArchiveColumn) {
		return fmt.Errorf("sqladapter: invalid table mapping")
	}
	seenManaged := make(map[Identifier]bool, len(table.Managed))
	for _, managed := range table.Managed {
		if !validIdentifier(managed.Column) || seenManaged[managed.Column] || managed.Column == table.IDColumn || managed.Column == table.VersionColumn {
			return fmt.Errorf("sqladapter: invalid managed column")
		}
		seenManaged[managed.Column] = true
		if !validManagedValue(managed.OnCreate) || !validManagedValue(managed.OnUpdate) {
			return fmt.Errorf("sqladapter: invalid managed value")
		}
	}
	return nil
}

func validManagedValue(value ManagedValue) bool {
	switch value.Source {
	case ManagedValueNone:
		return value.ScopeKey == ""
	case ManagedValueScope:
		return value.ScopeKey != ""
	case ManagedValueUTCNow:
		return value.ScopeKey == ""
	default:
		return false
	}
}

func validIdentifier(identifier Identifier) bool {
	return identifierPattern.MatchString(string(identifier))
}

func cloneTable(table TableDefinition) TableDefinition {
	clone := table
	clone.ScopeColumns = make(map[string]Identifier, len(table.ScopeColumns))
	for key, value := range table.ScopeColumns {
		clone.ScopeColumns[key] = value
	}
	clone.Fields = make(map[crud.FieldKey]Identifier, len(table.Fields))
	for key, value := range table.Fields {
		clone.Fields[key] = value
	}
	clone.Managed = append([]ManagedColumn(nil), table.Managed...)
	if table.ArchiveState != nil {
		state := *table.ArchiveState
		clone.ArchiveState = &state
	}
	return clone
}

func (source *SimpleTable) where(scope crud.Scope, query crud.Query) (string, []any, error) {
	where, args, err := source.scopeWhere(scope)
	if err != nil {
		return "", nil, err
	}
	if !query.IncludeArchived {
		activeWhere, activeArgs := source.activeWhere()
		where += activeWhere
		args = append(args, activeArgs...)
	}
	for _, filter := range query.Filters {
		column, ok := source.table.Fields[filter.Field]
		if !ok {
			return "", nil, public(crud.ErrorInvalidRequest)
		}
		if filter.Operator == crud.FilterIn {
			if len(filter.Values) == 0 || len(filter.Values) > 100 {
				return "", nil, public(crud.ErrorInvalidRequest)
			}
			where += " AND " + quote(column) + " IN (" + lookupPlaceholders(len(filter.Values)) + ")"
			args = append(args, filter.Values...)
			continue
		}
		operator, ok := filterOperator(filter.Operator)
		if !ok {
			return "", nil, public(crud.ErrorInvalidRequest)
		}
		where += " AND " + quote(column) + " " + operator
		if filter.Operator != crud.FilterIsNull {
			args = append(args, filter.Value)
		}
	}
	if query.Search != "" {
		fields := source.fieldColumns()
		if len(fields) == 0 {
			return "", nil, public(crud.ErrorInvalidRequest)
		}
		terms := make([]string, 0, len(fields))
		for _, column := range fields {
			terms = append(terms, "LOWER(CAST("+quote(column)+" AS TEXT)) LIKE LOWER(?)")
			args = append(args, "%"+query.Search+"%")
		}
		where += " AND (" + strings.Join(terms, " OR ") + ")"
	}
	return where, args, nil
}

func (source *SimpleTable) scopeWhere(scope crud.Scope) (string, []any, error) {
	if len(source.table.ScopeColumns) == 0 {
		if !source.table.Global {
			return "", nil, public(crud.ErrorForbidden)
		}
		return "1=1", nil, nil
	}
	keys := make([]string, 0, len(source.table.ScopeColumns))
	for key := range source.table.ScopeColumns {
		if scope[key] == "" {
			return "", nil, public(crud.ErrorForbidden)
		}
		keys = append(keys, key)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	args := make([]any, 0, len(keys))
	for _, key := range keys {
		parts = append(parts, quote(source.table.ScopeColumns[key])+" = ?")
		args = append(args, scope[key])
	}
	return strings.Join(parts, " AND "), args, nil
}

func (source *SimpleTable) activeWhere() (string, []any) {
	column, active, _, ok := source.archiveState()
	if !ok {
		return "", nil
	}
	if source.table.ArchiveColumn != nil {
		return " AND (" + quote(column) + " IS NULL OR " + quote(column) + " = 0)", nil
	}
	return " AND " + quote(column) + " = ?", []any{active}
}

func (source *SimpleTable) archiveState() (Identifier, crud.Value, crud.Value, bool) {
	if source.table.ArchiveState != nil {
		return source.table.ArchiveState.Column, source.table.ArchiveState.ActiveValue, source.table.ArchiveState.ArchivedValue, true
	}
	if source.table.ArchiveColumn != nil {
		return *source.table.ArchiveColumn, int64(0), int64(1), true
	}
	return "", nil, nil, false
}

func (source *SimpleTable) selectColumns() string {
	columns := []string{quote(source.table.IDColumn), quote(source.table.VersionColumn)}
	for _, field := range source.fieldColumns() {
		columns = append(columns, quote(field))
	}
	if column, _, _, ok := source.archiveState(); ok {
		columns = append(columns, quote(column))
	}
	return strings.Join(columns, ", ")
}

func (source *SimpleTable) fieldColumns() []Identifier {
	keys := make([]string, 0, len(source.table.Fields))
	for key := range source.table.Fields {
		keys = append(keys, string(key))
	}
	sort.Strings(keys)
	columns := make([]Identifier, 0, len(keys))
	for _, key := range keys {
		columns = append(columns, source.table.Fields[crud.FieldKey(key)])
	}
	return columns
}

func (source *SimpleTable) fieldKeys() []crud.FieldKey {
	keys := make([]string, 0, len(source.table.Fields))
	for key := range source.table.Fields {
		keys = append(keys, string(key))
	}
	sort.Strings(keys)
	fields := make([]crud.FieldKey, 0, len(keys))
	for _, key := range keys {
		fields = append(fields, crud.FieldKey(key))
	}
	return fields
}

func (source *SimpleTable) order(sortTerms []crud.Sort) string {
	terms := make([]string, 0, len(sortTerms))
	for _, term := range sortTerms {
		column := source.table.IDColumn
		if term.Field != "id" {
			column = source.table.Fields[term.Field]
		}
		if column == "" {
			return ""
		}
		direction := "ASC"
		if term.Direction == crud.SortDescending {
			direction = "DESC"
		}
		terms = append(terms, quote(column)+" "+direction)
	}
	if len(terms) == 0 {
		terms = append(terms, quote(source.table.IDColumn)+" ASC")
	}
	return " ORDER BY " + strings.Join(terms, ", ")
}

func (source *SimpleTable) mutationValues(scope crud.Scope, mutation crud.Mutation, action crud.Action) ([]string, []string, []any, error) {
	where, scopeArgs, err := source.scopeWhere(scope)
	if err != nil {
		return nil, nil, nil, err
	}
	_ = where
	columns := make([]string, 0, len(scopeArgs)+len(source.table.Fields))
	values := make([]string, 0, cap(columns))
	args := make([]any, 0, cap(columns))
	scopeKeys := make([]string, 0, len(source.table.ScopeColumns))
	for key := range source.table.ScopeColumns {
		scopeKeys = append(scopeKeys, key)
	}
	sort.Strings(scopeKeys)
	for _, key := range scopeKeys {
		columns = append(columns, quote(source.table.ScopeColumns[key]))
		values = append(values, "?")
		args = append(args, scope[key])
	}
	for _, key := range source.fieldKeys() {
		if action != crud.ActionCreate && key == source.table.IDField {
			continue
		}
		columns = append(columns, quote(source.table.Fields[key]))
		values = append(values, "?")
		args = append(args, mutation.Fields[key])
	}
	managedColumns, managedValues, managedArgs, err := source.managedValues(scope, action)
	if err != nil {
		return nil, nil, nil, err
	}
	columns = append(columns, managedColumns...)
	values = append(values, managedValues...)
	args = append(args, managedArgs...)
	if action == crud.ActionCreate && source.table.ArchiveState != nil {
		columns = append(columns, quote(source.table.ArchiveState.Column))
		values = append(values, "?")
		args = append(args, source.table.ArchiveState.ActiveValue)
	}
	return columns, values, args, nil
}

func (source *SimpleTable) assignments(action crud.Action) string {
	parts := make([]string, 0, len(source.table.Fields)+len(source.table.Managed)+1)
	for _, key := range source.fieldKeys() {
		if action != crud.ActionCreate && key == source.table.IDField {
			continue
		}
		parts = append(parts, quote(source.table.Fields[key])+" = ?")
	}
	for _, managed := range source.table.Managed {
		value := managed.OnUpdate
		if action == crud.ActionCreate {
			value = managed.OnCreate
		}
		if value.Source != ManagedValueNone {
			parts = append(parts, quote(managed.Column)+" = ?")
		}
	}
	parts = append(parts, quote(source.table.VersionColumn)+" = "+quote(source.table.VersionColumn)+" + 1")
	return strings.Join(parts, ", ")
}

func (source *SimpleTable) managedValues(scope crud.Scope, action crud.Action) ([]string, []string, []any, error) {
	columns := make([]string, 0, len(source.table.Managed))
	values := make([]string, 0, len(source.table.Managed))
	args := make([]any, 0, len(source.table.Managed))
	for _, managed := range source.table.Managed {
		value := managed.OnUpdate
		if action == crud.ActionCreate {
			value = managed.OnCreate
		}
		if value.Source == ManagedValueNone {
			continue
		}
		resolved, err := resolveManagedValue(scope, value)
		if err != nil {
			return nil, nil, nil, err
		}
		columns = append(columns, quote(managed.Column))
		values = append(values, "?")
		args = append(args, resolved)
	}
	return columns, values, args, nil
}

func resolveManagedValue(scope crud.Scope, value ManagedValue) (any, error) {
	switch value.Source {
	case ManagedValueScope:
		resolved := scope[value.ScopeKey]
		if resolved == "" {
			return nil, public(crud.ErrorForbidden)
		}
		return resolved, nil
	case ManagedValueUTCNow:
		return time.Now().UTC().Format(time.RFC3339Nano), nil
	default:
		return nil, public(crud.ErrorInvalidRequest)
	}
}

func (source *SimpleTable) archiveAssignments(scope crud.Scope, archiveColumn Identifier, archived crud.Value) (string, []any, error) {
	parts := []string{quote(archiveColumn) + " = ?"}
	args := []any{archived}
	_, _, managedArgs, err := source.managedValues(scope, crud.ActionUpdate)
	if err != nil {
		return "", nil, err
	}
	for _, managed := range source.table.Managed {
		if managed.OnUpdate.Source != ManagedValueNone {
			parts = append(parts, quote(managed.Column)+" = ?")
		}
	}
	args = append(args, managedArgs...)
	parts = append(parts, quote(source.table.VersionColumn)+" = "+quote(source.table.VersionColumn)+" + 1")
	return strings.Join(parts, ", "), args, nil
}

func (source *SimpleTable) records(rows *sql.Rows) ([]crud.Record, error) {
	var records []crud.Record
	for rows.Next() {
		record, err := source.scanRecord(rows)
		if err != nil {
			return nil, err
		}
		records = append(records, record)
	}
	return records, nil
}

type scanner interface{ Scan(...any) error }

func (source *SimpleTable) scanRecord(row scanner) (crud.Record, error) {
	var id any
	var version int64
	keys := source.fieldKeys()
	values := make([]any, len(keys))
	destinations := make([]any, 0, len(keys)+2)
	destinations = append(destinations, &id, &version)
	for index := range values {
		destinations = append(destinations, &values[index])
	}
	var archiveValue any
	if _, _, _, ok := source.archiveState(); ok {
		destinations = append(destinations, &archiveValue)
	}
	if err := row.Scan(destinations...); err != nil {
		return crud.Record{}, err
	}
	fields := make(crud.Fields, len(keys))
	for index, key := range keys {
		fields[key] = sqlValue(values[index])
	}
	return crud.Record{ID: crud.RecordID(stringValue(id)), Version: crud.Version(version), Fields: fields, Archived: source.isArchivedValue(archiveValue)}, nil
}

func (source *SimpleTable) isArchivedValue(value any) bool {
	_, active, archived, ok := source.archiveState()
	if !ok {
		return false
	}
	value = sqlValue(value)
	if source.table.ArchiveColumn != nil {
		switch typed := value.(type) {
		case nil:
			return false
		case bool:
			return typed
		case int64:
			return typed != 0
		case int:
			return typed != 0
		default:
			return stringValue(typed) != "0" && stringValue(typed) != ""
		}
	}
	return archiveValuesEqual(value, archived) && !archiveValuesEqual(value, active)
}

func archiveValuesEqual(left, right any) bool {
	left = sqlValue(left)
	right = sqlValue(right)
	if left == nil || right == nil {
		return left == nil && right == nil
	}
	if leftBool, ok := left.(bool); ok {
		rightBool, rightOK := right.(bool)
		return rightOK && leftBool == rightBool
	}
	if rightBool, ok := right.(bool); ok {
		leftBool, leftOK := left.(bool)
		return leftOK && leftBool == rightBool
	}
	if leftInteger, ok := left.(int64); ok {
		rightInteger, rightOK := right.(int64)
		return rightOK && leftInteger == rightInteger
	}
	if rightInteger, ok := right.(int64); ok {
		leftInteger, leftOK := left.(int64)
		return leftOK && leftInteger == rightInteger
	}
	return fmt.Sprint(left) == fmt.Sprint(right)
}

func filterOperator(operator crud.FilterOperator) (string, bool) {
	switch operator {
	case crud.FilterEqual:
		return "= ?", true
	case crud.FilterNotEqual:
		return "<> ?", true
	case crud.FilterLessThan:
		return "< ?", true
	case crud.FilterLessOrEqual:
		return "<= ?", true
	case crud.FilterGreaterThan:
		return "> ?", true
	case crud.FilterGreaterOrEqual:
		return ">= ?", true
	case crud.FilterContains:
		return "LIKE '%' || ? || '%'", true
	case crud.FilterPrefix:
		return "LIKE ? || '%'", true
	case crud.FilterIsNull:
		return "IS NULL", true
	default:
		return "", false
	}
}

func quote(identifier Identifier) string { return quoteRaw(string(identifier)) }

func quoteRaw(identifier string) string { return `"` + strings.ReplaceAll(identifier, `"`, `""`) + `"` }

func public(code crud.ErrorCode) *crud.Error {
	return &crud.Error{Code: code, Message: crud.MessageCode("crud.error." + string(code))}
}

func isForeignKeyViolation(err error) bool {
	if err == nil {
		return false
	}
	message := strings.ToLower(err.Error())
	return strings.Contains(message, "foreign key constraint failed") ||
		strings.Contains(message, "foreign key constraint violation")
}

func stringValue(value any) string {
	if bytes, ok := value.([]byte); ok {
		return string(bytes)
	}
	return fmt.Sprint(value)
}
func sqlValue(value any) any {
	if bytes, ok := value.([]byte); ok {
		return string(bytes)
	}
	return value
}
