-- Disposable fixture for the clear-crud renderer demo. It is not product data.
DROP TABLE IF EXISTS clear_crud_minimal_demo_contacts;
DROP TABLE IF EXISTS clear_crud_enum_controls_demo;
DROP TABLE IF EXISTS clear_crud_disposable_junk_contacts;
DROP TABLE IF EXISTS clear_crud_reference_lookup_demo;
DROP TABLE IF EXISTS clear_crud_reference_cities;
DROP TABLE IF EXISTS clear_crud_reference_regions;
DROP TABLE IF EXISTS clear_crud_reference_states;
DROP TABLE IF EXISTS clear_crud_reference_values;
DROP TABLE IF EXISTS clear_crud_auxiliary_catalog_lookup_demo;
DROP TABLE IF EXISTS clear_crud_auxiliary_catalog_options;
DROP TABLE IF EXISTS clear_crud_auxiliary_catalogs;

CREATE TABLE clear_crud_minimal_demo_contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tenant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    enabled BOOLEAN NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX idx_clear_crud_minimal_demo_contacts_listing
    ON clear_crud_minimal_demo_contacts (tenant_id, enabled, name);

WITH RECURSIVE numbers(value) AS (
    SELECT 1
    UNION ALL
    SELECT value + 1 FROM numbers WHERE value < 100
)
INSERT INTO clear_crud_minimal_demo_contacts (tenant_id, name, notes, status, enabled, version)
SELECT
    'demo_tenant_alpha',
    printf('Minimal default contact %03d', value),
    printf('Generated by the table-only CRUD definition %03d.', value),
    CASE value % 3 WHEN 0 THEN 'new' WHEN 1 THEN 'review' ELSE 'closed' END,
    CASE WHEN value % 9 = 0 THEN 0 ELSE 1 END,
    1
FROM numbers;

-- Small synthetic catalog used only to smoke-test global dependent lookups.
-- The engine has no knowledge of geography; a real consumer can register FIPE,
-- Correios, airline or any other catalog with the same contract.
CREATE TABLE clear_crud_reference_values (
    id INTEGER PRIMARY KEY,
    kind TEXT NOT NULL,
    name TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_clear_crud_reference_values_kind_name ON clear_crud_reference_values (kind, name);
INSERT INTO clear_crud_reference_values (id, kind, name) VALUES
    (1, 'state', 'São Paulo'),
    (2, 'state', 'Paraná'),
    (3, 'state', 'Acre'),
    (4, 'state', 'Alagoas'),
    (5, 'state', 'Amapá'),
    (6, 'state', 'Amazonas'),
    (7, 'state', 'Bahia'),
    (8, 'state', 'Ceará'),
    (9, 'state', 'Distrito Federal'),
    (10, 'state', 'Espírito Santo'),
    (11, 'state', 'Goiás'),
    (12, 'state', 'Maranhão'),
    (13, 'state', 'Mato Grosso'),
    (14, 'state', 'Mato Grosso do Sul'),
    (15, 'state', 'Minas Gerais'),
    (16, 'state', 'Pará'),
    (17, 'state', 'Paraíba'),
    (18, 'state', 'Pernambuco'),
    (19, 'state', 'Piauí'),
    (20, 'state', 'Rio de Janeiro'),
    (21, 'state', 'Rio Grande do Norte'),
    (22, 'state', 'Rio Grande do Sul'),
    (23, 'state', 'Rondônia'),
    (24, 'state', 'Roraima'),
    (25, 'state', 'Santa Catarina'),
    (26, 'state', 'Sergipe'),
    (27, 'state', 'Tocantins'),
    (101, 'currency', 'Real');

-- Contract: clear.catalog.auxiliary.v1. Four small catalogs share one options table.
CREATE TABLE clear_crud_auxiliary_catalogs (
    id INTEGER PRIMARY KEY, tenant_id TEXT NOT NULL, code INTEGER NOT NULL, title TEXT NOT NULL,
    max_options INTEGER NOT NULL, active BOOLEAN NOT NULL DEFAULT 1, management TEXT NOT NULL,
    value_1_label TEXT NOT NULL, value_1_type TEXT NOT NULL, value_1_required BOOLEAN NOT NULL,
    value_2_label TEXT NOT NULL, value_2_type TEXT NOT NULL, value_2_required BOOLEAN NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE clear_crud_auxiliary_catalog_options (
    id INTEGER PRIMARY KEY, tenant_id TEXT NOT NULL, catalog_id TEXT NOT NULL REFERENCES clear_crud_auxiliary_catalogs(id),
    sequence INTEGER NOT NULL, value_1 TEXT NOT NULL, value_2 TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL, version INTEGER NOT NULL DEFAULT 1,
    UNIQUE (catalog_id, sequence)
);
CREATE INDEX idx_clear_crud_auxiliary_catalogs_listing ON clear_crud_auxiliary_catalogs (tenant_id, active, title);
CREATE INDEX idx_clear_crud_auxiliary_catalog_options_lookup ON clear_crud_auxiliary_catalog_options (tenant_id, catalog_id, active, sort_order, value_1);
CREATE INDEX idx_clear_crud_auxiliary_catalog_options_listing ON clear_crud_auxiliary_catalog_options (tenant_id, catalog_id, sort_order);
INSERT INTO clear_crud_auxiliary_catalogs (id, tenant_id, code, title, max_options, management, value_1_label, value_1_type, value_1_required, value_2_label, value_2_type, value_2_required) VALUES
    (10, 'demo_tenant_alpha', 10, 'Estados', 99, 'fixed', 'Sigla', 'text', 1, 'Nome', 'text', 0),
    (20, 'demo_tenant_alpha', 20, 'Territórios', 99, 'fixed', 'Código', 'text', 1, 'Nome', 'text', 0),
    (30, 'demo_tenant_alpha', 30, 'Canais', 20, 'fixed', 'Código', 'text', 1, 'Nome', 'text', 0),
    (40, 'demo_tenant_alpha', 40, 'Prioridades', 10, 'fixed', 'Código', 'text', 1, 'Nome', 'text', 0);
INSERT INTO clear_crud_auxiliary_catalog_options (id, tenant_id, catalog_id, sequence, value_1, value_2, active, sort_order) VALUES
    (1001, 'demo_tenant_alpha', 10, 1, 'SP', 'São Paulo', 1, 10), (1002, 'demo_tenant_alpha', 10, 2, 'PR', 'Paraná', 1, 20),
    (2001, 'demo_tenant_alpha', 20, 1, 'DF', 'Distrito Federal', 1, 10), (2002, 'demo_tenant_alpha', 20, 2, 'FN', 'Fernando de Noronha', 1, 20),
    (2003, 'demo_tenant_alpha', 20, 3, 'OLD', 'Território inativo', 0, 30),
    (3001, 'demo_tenant_alpha', 30, 1, 'email', 'E-mail', 1, 10), (3002, 'demo_tenant_alpha', 30, 2, 'phone', 'Telefone', 1, 20),
    (3003, 'demo_tenant_alpha', 30, 3, 'whatsapp', 'WhatsApp', 1, 30), (3004, 'demo_tenant_alpha', 30, 4, 'FAX', 'Canal inativo', 0, 40),
    (4001, 'demo_tenant_alpha', 40, 1, 'LOW', 'Baixa', 1, 10), (4002, 'demo_tenant_alpha', 40, 2, 'HIGH', 'Alta', 1, 20);
CREATE TABLE clear_crud_auxiliary_catalog_lookup_demo (
    id INTEGER PRIMARY KEY AUTOINCREMENT, tenant_id TEXT NOT NULL, name TEXT NOT NULL,
    selected_option TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_clear_crud_auxiliary_catalog_lookup_demo_listing ON clear_crud_auxiliary_catalog_lookup_demo (tenant_id, name);
INSERT INTO clear_crud_auxiliary_catalog_lookup_demo (tenant_id, name, selected_option) VALUES
    ('demo_tenant_alpha', 'Seleção de território', 'DF'),
    ('demo_tenant_alpha', 'Seleção de estado', 'SP'),
    ('demo_tenant_alpha', 'Seleção de estado alternativo', 'PR');

CREATE TABLE clear_crud_reference_regions (
    id INTEGER PRIMARY KEY,
    state_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_clear_crud_reference_regions_state_name ON clear_crud_reference_regions (state_id, name);
INSERT INTO clear_crud_reference_regions (id, state_id, name) VALUES
    (11, 1, 'Região Metropolitana de São Paulo'),
    (12, 1, 'Vale do Paraíba'),
    (21, 2, 'Região Metropolitana de Curitiba');

CREATE TABLE clear_crud_reference_cities (
    id INTEGER PRIMARY KEY,
    region_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_clear_crud_reference_cities_region_name ON clear_crud_reference_cities (region_id, name);
INSERT INTO clear_crud_reference_cities (id, region_id, name) VALUES
    (111, 11, 'São Paulo'), (112, 11, 'Osasco'), (121, 12, 'Taubaté'), (211, 21, 'Curitiba');

CREATE TABLE clear_crud_reference_lookup_demo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tenant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    state_id INTEGER NOT NULL,
    region_id INTEGER NOT NULL,
    city_id INTEGER NOT NULL,
    version INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX idx_clear_crud_reference_lookup_demo_listing ON clear_crud_reference_lookup_demo (tenant_id, name);
INSERT INTO clear_crud_reference_lookup_demo (tenant_id, name, state_id, region_id, city_id)
VALUES
    ('demo_tenant_alpha', 'Contato São Paulo', 1, 11, 111),
    ('demo_tenant_alpha', 'Contato Osasco', 1, 11, 112),
    ('demo_tenant_alpha', 'Contato Taubaté', 1, 12, 121),
    ('demo_tenant_alpha', 'Contato Curitiba', 2, 21, 211);

CREATE TABLE clear_crud_enum_controls_demo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tenant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high')),
    channel TEXT NOT NULL CHECK (channel IN ('email', 'phone', 'whatsapp')),
    state TEXT NOT NULL CHECK (state IN ('draft', 'active', 'closed')),
    tone TEXT NOT NULL CHECK (tone IN ('info', 'warning', 'urgent')),
    version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX idx_clear_crud_enum_controls_demo_listing
    ON clear_crud_enum_controls_demo (tenant_id, name);

WITH RECURSIVE numbers(value) AS (
    SELECT 1
    UNION ALL
    SELECT value + 1 FROM numbers WHERE value < 12
)
INSERT INTO clear_crud_enum_controls_demo (tenant_id, name, priority, channel, state, tone, version)
SELECT
    'demo_tenant_alpha',
    printf('Enum control sample %03d', value),
    CASE value % 3 WHEN 0 THEN 'low' WHEN 1 THEN 'medium' ELSE 'high' END,
    CASE value % 3 WHEN 0 THEN 'email' WHEN 1 THEN 'phone' ELSE 'whatsapp' END,
    CASE value % 3 WHEN 0 THEN 'draft' WHEN 1 THEN 'active' ELSE 'closed' END,
    CASE value % 3 WHEN 0 THEN 'info' WHEN 1 THEN 'warning' ELSE 'urgent' END,
    1
FROM numbers;

CREATE TABLE clear_crud_disposable_junk_contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tenant_id TEXT NOT NULL,
    name VARCHAR(120) NOT NULL,
    notes TEXT,
    status VARCHAR(16) NOT NULL DEFAULT 'new',
    enabled BOOLEAN NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 1,
    archived INTEGER NOT NULL DEFAULT 0,
    zextra_01 TEXT,
    zextra_02 TEXT,
    zextra_03 TEXT,
    zextra_04 TEXT,
    zextra_05 TEXT,
    zextra_06 TEXT,
    zextra_07 TEXT,
    zextra_08 TEXT,
    zextra_09 TEXT,
    zextra_10 TEXT,
    zextra_11 TEXT,
    zextra_12 TEXT,
    zextra_13 TEXT
);

CREATE INDEX idx_clear_crud_disposable_junk_contacts_listing
    ON clear_crud_disposable_junk_contacts (tenant_id, enabled, name);

WITH RECURSIVE numbers(value) AS (
    SELECT 1
    UNION ALL
    SELECT value + 1 FROM numbers WHERE value < 100
)
INSERT INTO clear_crud_disposable_junk_contacts (
    tenant_id, name, notes, status, enabled, version, archived,
    zextra_01, zextra_02, zextra_03, zextra_04, zextra_05, zextra_06,
    zextra_07, zextra_08, zextra_09, zextra_10, zextra_11, zextra_12,
    zextra_13
)
SELECT
    'demo_tenant_alpha',
    printf('Disposable junk contact %03d', value),
    printf('Synthetic record %03d for the renderer preview only.', value),
    CASE value % 3 WHEN 0 THEN 'new' WHEN 1 THEN 'review' ELSE 'closed' END,
    CASE WHEN value % 9 = 0 THEN 0 ELSE 1 END,
    1,
    CASE WHEN value % 10 = 0 THEN 1 ELSE 0 END,
    printf('Demo field 01 %03d', value),
    printf('Demo field 02 %03d', value),
    printf('Demo field 03 %03d', value),
    printf('Demo field 04 %03d', value),
    printf('Demo field 05 %03d', value),
    printf('Demo field 06 %03d', value),
    printf('Demo field 07 %03d', value),
    printf('Demo field 08 %03d', value),
    printf('Demo field 09 %03d', value),
    printf('Demo field 10 %03d', value),
    printf('Demo field 11 %03d', value),
    printf('Demo field 12 %03d', value),
    printf('Demo field 13 %03d', value)
FROM numbers;
